server:
  port: 8081


spring:
  application:
    name: project1
  jpa:
    hibernate:
      ddl-auto: create
      ddl-import_files: data.sql


  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    platform: h2


  h2:
    console:
      enabled: true
      path: /console



  endpoints:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      sensitive: false

  management:
  contextPath: /manage

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    preferIpAddress: true

